CREATE TABLE task_categories
(
    category_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name        VARCHAR(200)                            NOT NULL,
    category_description VARCHAR(500),
    CONSTRAINT pk_task_categories PRIMARY KEY (category_id)
);

CREATE TABLE tasks
(
    task_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_name               VARCHAR(100)                            NOT NULL,
    task_description        VARCHAR(500),
    deadline                TIMESTAMP                               NOT NULL,
    category_id_category_id BIGINT,
    CONSTRAINT pk_tasks PRIMARY KEY (task_id)
);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_CATEGORY_ID_CATEGORY FOREIGN KEY (category_id_category_id) REFERENCES task_categories (category_id);