name: Java CI with Gradle todoApplication
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This step uses the actions/checkout action to download a copy of your repository on the runner
      - name: download a copy of the repository on the runner
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # the build task will download dependencies, build classes, run tests, and package classes into their distributable format
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments:  -b ci.gradle package

