name: Java CI with Gradle todoApplication
define: &SONAR_TOKEN fe7c298524a15ddefbc77a1e9435d5a2f871fb97
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This step uses the actions/checkout action to download a copy of your repository on the runner
      - name: download a copy of the repository on the runner
        uses: actions/checkout@v3

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # the build task will download dependencies, build classes, run tests, and package classes into their distributable format
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: sonar
        run: ./gradlew sonar
